version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USER=username
        - DB_PASSWORD=postgres
        - DB_NAME=password
    volumes:
      - .:/src

    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
